language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
  - ree
before_install:
  - gem update --system
  - gem --version # make sure rubygems actually were updated
script: bundle exec rake test
gemfile:
  - gemfiles/activerecord3_0.gemfile
  - gemfiles/activerecord3_1.gemfile
  - gemfiles/activerecord3_2.gemfile
